packages:
  - apps/*
  - packages/*
  - scripts/*
catalog:
  zod: ^3.25.67
  better-auth: ^1.2.10
  autumn-js: ^0.0.66
  superjson: ^2.2.2
  '@trpc/server': ^11.4.2
  '@trpc/client': ^11.4.2
  '@trpc/tanstack-react-query': ^11.4.2
  wrangler: ^4.20.5
  typescript: ^5.8.3
  drizzle-orm: ^0.44.2
  drizzle-kit: ^0.31.1
  '@types/node': ^24.0.3
  'react': ^19.1.0
  'react-dom': ^19.1.0
onlyBuiltDependencies:
  - core-js
  - core-js-pure
  - esbuild
  - sharp
  - unrs-resolver
  - workerd
patchedDependencies:
  novel: patches/novel.patch
