name: autofix.ci

on:
  pull_request:

jobs:
  autofix:
    runs-on: blacksmith-4vcpu-ubuntu-2204
    steps:
      - name: Checkout Code 🛎
        uses: actions/checkout@v4

      - name: Setup Bun 🌟
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Setup Node 📦
        uses: useblacksmith/setup-node@v5
        with:
          node-version: latest

      - name: Install dependencies 📦
        run: bun install
